export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const GET_ARTISTS = 'GET_ARTISTS';
export const ARTIST_LOADING = 'ARTIST_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';